// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4fippP8gNsvrrD25O_-utfBpJrLO01G0',
    appId: '1:1028414827330:web:016d8a2a329f6bcef036db',
    messagingSenderId: '1028414827330',
    projectId: 'fatec-ride-e6fa3',
    authDomain: 'fatec-ride-e6fa3.firebaseapp.com',
    storageBucket: 'fatec-ride-e6fa3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_C9ffK2xhTFUmOzPDX07Q7BBGmOJUCk',
    appId: '1:1028414827330:android:fd90fa8cb94dd88ff036db',
    messagingSenderId: '1028414827330',
    projectId: 'fatec-ride-e6fa3',
    storageBucket: 'fatec-ride-e6fa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJjfYdyJ0eeyYmsi2myaC7qCIkTpvQWvw',
    appId: '1:1028414827330:ios:df7e2829fd28b7a4f036db',
    messagingSenderId: '1028414827330',
    projectId: 'fatec-ride-e6fa3',
    storageBucket: 'fatec-ride-e6fa3.firebasestorage.app',
    iosBundleId: 'com.example.apps',
  );

}